import os
import logging
import requests
from typing import Optional, Dict, Any

class MistralAPI:
    def __init__(self):
        """Initialize the Mistral API client."""
        self.api_key = os.getenv("MISTRAL_API_KEY")
        if not self.api_key:
            logging.error("MISTRAL_API_KEY not found in environment variables")
            raise ValueError("MISTRAL_API_KEY environment variable is required")
        
        self.base_url = "https://api.mistral.ai/v1"
        self.model = "mistral-small-latest"
        logging.info(f"Initialized MistralAPI with model: {self.model}")
        
    def generate_summary(self, text: str, max_tokens: Optional[int] = 300) -> Optional[str]:
        """
        Generate a concise executive summary using the Mistral API.
        
        Args:
            text: The text to summarize
            max_tokens: Maximum number of tokens in the response
            
        Returns:
            Optional[str]: The generated summary or None if the API call fails
        """
        try:
            # Log request details
            logging.debug(f"Preparing Mistral API request with max_tokens={max_tokens}")
            logging.debug(f"Input text length: {len(text)} characters")
            
            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            }
            
            messages = [
                {
                    "role": "system",
                    "content": """You are an expert at creating concise executive summaries. 
                    Your task is to generate a 3-bullet point summary of no more than 100 words total.
                    Each bullet point should be a key insight or finding.
                    
                    When citing sources:
                    - Always use the direct URLs provided in the source information
                    - For academic papers, use both the DOI and direct URL if available
                    - Format citations as HTML links: <a href="URL">Source Name</a>
                    - Include author names and publication venue when available
                    - For academic papers, include citation count if available
                    - For podcasts, include duration and series name
                    - For emails, use the link from the title if available
                    - For RSS articles, include publication date
                    
                    Format the response as HTML with proper bullet points and links.
                    Be concise and focus on the most important information.
                    Do not include code blocks or any content outside of <ul>, <ol>, and <li> tags."""
                },
                {
                    "role": "user",
                    "content": f"Please create a concise 3-bullet point executive summary of the following content:\n\n{text}"
                }
            ]
            
            data = {
                "model": self.model,
                "messages": messages,
                "max_tokens": max_tokens,
                "temperature": 0.2,
                "top_p": 0.9
            }
            
            # Log API call details
            logging.debug(f"Making request to Mistral API endpoint: {self.base_url}/chat/completions")
            logging.debug(f"Request parameters: model={self.model}, temperature=0.2, top_p=0.9")
            
            response = requests.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=data,
                timeout=90  # Increased for PythonAnywhere proxy latency
            )
            
            # Log response details
            logging.debug(f"Mistral API response status code: {response.status_code}")
            logging.debug(f"Mistral API response headers: {dict(response.headers)}")
            
            response.raise_for_status()
            result = response.json()
            
            # Log response content (excluding sensitive data)
            if result and 'choices' in result and result['choices']:
                logging.debug("Successfully received response from Mistral API")
                logging.debug(f"Response contains {len(result['choices'])} choices")
                
                summary = result['choices'][0]['message']['content']
                # Ensure the summary is properly formatted as HTML
                if not summary.startswith("<ul>"):
                    summary = f"<ul>{summary}</ul>"
                # Add attribution note below the summary
                attribution = '<div style="font-size: 0.8em; color: #666; margin-top: 10px; font-style: italic;">Summary generated by Mistral AI</div>'
                logging.info("Successfully generated executive summary using Mistral API")
                logging.debug(f"Generated summary length: {len(summary)} characters")
                return f"{summary}\n{attribution}"
            
            logging.warning("Empty response from Mistral API - will use fallback summary")
            logging.debug(f"Response content: {result}")
            return None
            
        except requests.exceptions.RequestException as e:
            logging.warning(f"Error calling Mistral API - will use fallback summary: {str(e)}")
            # Log more details about the request exception
            if hasattr(e, 'response'):
                logging.warning(f"Response status code: {e.response.status_code}")
                logging.warning(f"Response content: {e.response.text}")
                logging.warning(f"Response headers: {dict(e.response.headers)}")
            return None
        except Exception as e:
            logging.warning(f"Unexpected error calling Mistral API - will use fallback summary: {str(e)}")
            logging.exception("Full traceback:")  # This will log the full stack trace
            return None 