import os
import logging
import requests
from typing import Optional, Dict, Any

class MistralAPI:
    def __init__(self):
        """Initialize the Mistral API client."""
        self.api_key = os.getenv("MISTRAL_API_KEY")
        if not self.api_key:
            logging.error("MISTRAL_API_KEY not found in environment variables")
            raise ValueError("MISTRAL_API_KEY environment variable is required")
        
        self.base_url = "https://api.mistral.ai/v1"
        self.model = "mistral-small-latest"
        
    def generate_summary(self, text: str, max_tokens: Optional[int] = 300) -> Optional[str]:
        """
        Generate a concise executive summary using the Mistral API.
        
        Args:
            text: The text to summarize
            max_tokens: Maximum number of tokens in the response
            
        Returns:
            Optional[str]: The generated summary or None if the API call fails
        """
        try:
            headers = {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            }
            
            messages = [
                {
                    "role": "system",
                    "content": """You are an expert at creating concise executive summaries. 
                    Your task is to generate a 3-bullet point summary of no more than 100 words total.
                    Each bullet point should be a key insight or finding.
                    Include source citations and links where available.
                    Format the response as HTML with proper bullet points and links.
                    Be concise and focus on the most important information.
                    Do not to include code blocks or any content outside of <ul>, <ol>, and <li> tags."""
                },
                {
                    "role": "user",
                    "content": f"Please create a concise 3-bullet point executive summary of the following content:\n\n{text}"
                }
            ]
            
            data = {
                "model": self.model,
                "messages": messages,
                "max_tokens": max_tokens,
                "temperature": 0.2,
                "top_p": 0.9
            }
            
            response = requests.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=data,
                timeout=60
            )
            
            response.raise_for_status()
            result = response.json()
            
            if result and 'choices' in result and result['choices']:
                summary = result['choices'][0]['message']['content']
                # Add attribution note below the summary
                attribution = '<div style="font-size: 0.8em; color: #666; margin-top: 10px; font-style: italic;">Summary generated by Mistral AI</div>'
                logging.info("Successfully generated executive summary using Mistral API")
                return f"{summary}\n{attribution}"
            
            logging.warning("Empty response from Mistral API - will use fallback summary")
            return None
            
        except requests.exceptions.RequestException as e:
            logging.warning(f"Error calling Mistral API - will use fallback summary: {str(e)}")
            return None
        except Exception as e:
            logging.warning(f"Unexpected error calling Mistral API - will use fallback summary: {str(e)}")
            return None 