#!/usr/bin/env python3
"""
Feeds configuration module for the ESG Newsletter System.
Handles RSS feeds and related configurations.
"""

# List of RSS feeds to fetch
RSS_FEEDS = [
    "https://www.bafin.de/DE/Service/TopNavigation/RSS/_function/rssnewsfeed.xml",
    "https://www.europarl.europa.eu/rss/doc/press-releases/en.xml",
    "https://www.europarl.europa.eu/rss/doc/last-news-committees/en.xml",
    "http://www.bankingsupervision.europa.eu/rss/press.html",
    "https://www.bankingsupervision.europa.eu/rss/pub.html",
    "https://officialblogofunio.com/feed/",
    "http://eucenterillinois.blogspot.com/feeds/posts/default",
    "https://ecfr.eu/feed/",
    "https://www.euractiv.com/?feed=mcfeed",
    "https://rss.nytimes.com/services/xml/rss/nyt/Europe.xml",
    "https://rss.sueddeutsche.de/alles",
    "https://newsfeed.zeit.de/index",
    "https://www.handelsblatt.com/contentexport/feed/schlagzeilen",
    "https://www.handelsblatt.com/contentexport/feed/politik",
    "https://www.europeanlawblog.eu/rss.xml",
    "http://www.feedly.com/home#subscription/feed/http://www.bruegel.org/rss?type=all",
    "https://ecfr.eu/feed/",
    "https://rss.dw.com/rdf/rss-en-all",
    "https://officialblogofunio.com/feed/",
    "https://www.europarl.europa.eu/rss/doc/top-stories/de.xml",
    "https://www.europarl.europa.eu/rss/doc/agendas-news/de.xml",
    "https://www.europarl.europa.eu/rss/doc/newsletters/de.xml",
    "https://www.nature.com/nclimate.rss",
    "http://wupperinst.org/rss_news_en.php",
    "http://feeds.harvardbusiness.org/harvardbusiness/videoideacast",
    "https://www.ilo.org/de/rss.xml",
    "http://feeds.harvardbusiness.org/harvardbusiness/",
    "https://ssir.org/site/rss_2.0",
    "https://insights.som.yale.edu/rss",
    "https://www.pik-potsdam.de/de/aktuelles/nachrichten/nachrichten/rss.xml",
    "https://www.ufz.de/index.php?de=34299&vera_rss",
    "https://www.ufz.de/index.php?de=18084&vera_rss",
    "https://www.jpmorgan.com/US/en/sitemap.xml",
    "https://www.imf.org/en/rss-list/feed?category=FANDD_ENG",
    "https://www.imf.org/en/News/RSS?TemplateID={2FA3421A-F179-46B6-B8D9-5C65CB4A6584}",
    "https://www.imf.org/en/news/rss?Language=ENG&Country=DEU",
    "https://www.imf.org/en/rss-list/feed?category=WHATSNEW",
    "https://www.imf.org/en/Publications/RSS?language=eng&series=World%20Economic%20Outlook",
    "https://www.imf.org/en/Publications/RSS?language=eng&series=IMF%20Working%20Papers",
    "https://www.imf.org/en/Publications/RSS?language=eng&series=Regional%20Economic%20Outlook",
    "https://www.leibniz-gemeinschaft.de/rss.xml",
    "http://feeds.harvardbusiness.org/harvardbusiness/videoideacast",
    "http://feeds.harvardbusiness.org/harvardbusiness?format=xml",
    "https://onlinelibrary.wiley.com/action/showFeed?jc=19447973&type=etoc&feed=rss",
    "https://ascelibrary.org/action/showFeed?type=etoc&feed=rss&jc=jwrmd5",
    "https://rss.sciencedirect.com/publication/science/13648152",
    "https://rss.sciencedirect.com/publication/science/03091708",
    "https://hydrol-earth-syst-sci.net/xml/rss2_0.xml",
    "https://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1752-1688",
    "https://rss.sciencedirect.com/publication/science/00221694",
    "https://iopscience.iop.org/1748-9326/?rss=1",
    "https://www.mitpressjournals.org/action/showFeed?ui=k928&mi=3il28u&ai=t9&jc=evco&type=etoc&feed=rss",
    "https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=10898&channel-name=Journal+of+Global+Optimization",
    "https://www.journals.elsevier.com/computers-and-operations-research/rss",
    "https://feeds.nature.com/nclimate/rss/current?format=xml",
    "https://cepr.org/rss/vox-content",
    "https://cepr.org/rss/discussion-paper",
    "https://cepr.org/rss/news",
    "https://cepr.org/rss/events",
    "https://www.tandfonline.com/feed/rss/tsfi20",
    "https://www.tandfonline.com/feed/rss/rcli20",
    "https://www.tandfonline.com/feed/rss/oaes21",
    "https://www.tandfonline.com/feed/rss/oabm20",
    "https://www.tandfonline.com/feed/rss/ufaj20",
    "https://www.tandfonline.com/feed/rss/raec20",
    "https://www.tandfonline.com/feed/rss/raec20",
    "https://www.tandfonline.com/feed/rss/rwin20",
    "https://www.tandfonline.com/feed/rss/tjem20",
    "https://www.tandfonline.com/feed/rss/tjds20",
    "https://www.tandfonline.com/feed/rss/tsue20",
    "https://www.tandfonline.com/feed/rss/tcpo20",
    "https://www.tandfonline.com/feed/rss/tcld20",
    "https://www.tandfonline.com/feed/rss/rero20",
    "https://www.tandfonline.com/feed/rss/rcls20",
    "https://www.tandfonline.com/feed/rss/raie20",
    "https://www.tandfonline.com/feed/rss/tjds20",
    "https://jpmorganchaseco.gcs-web.com/rss/news-releases.xml"
]

# Time thresholds
TIME_THRESHOLD = 24 * 3600  # 24 hours in seconds - for RSS and email collection
CLEANUP_THRESHOLD = 2  # Days - for email cleanup 